### PR TITLE
Proposed fixes for issue 81

### PR DESCRIPTION
**Pull request by bitsofinfo**
So basically this boiled down to creating some new implementations of serialize/deserialize that use ObjectOutputStream as well as support being called w/ optional compression (which might be useful due to SQS message size limits). 

The unit test still works and I added a new test for the transient referenced flagged TestObject with the special methods as described at http://docs.oracle.com/javase/7/docs/api/java/io/ObjectOutputStream.html to verify that if people want to send object messages w/ transient flagged fields AND they have these methods implemented, things will work as they expect.

Hopefully this fix can be put in, or some options to somehow enable the caller to decide which serialization engine to run that the project owner could discuss/implement? What do you think?

### CODE REVIEW

**Comment by carterpage** [comment]
Sorry for the long delay.  This looks good at first glance.  I'm going to take another more thorough review before I approve.

**Comment by bitsofinfo** [comment]
Agreed cause I'm not sure I consistently implemented the calls to the OO versions, i.e. There might be paths that still call the hessian version.

My bigger question is why was the hessian one used originally and should we make the OO serialization an configurable option as to not break back compatibility. I imagine that there are some behaviors if the hessian library that existing users are knowingly or unknowingly dependent on.....

**Comment by carterpage** [comment]
Did Hessian originally for size reasons, but a lot of users have complained
with this particular choice.  I'd love to make the OO serialization
configurable.  Please feel free to implement and submit a PR if you have
time.  We'd need to make hessian the default but we should allow a user to
plug in anything they want.

**Comment by carterpage** [comment]
I'm going to do some work on this this weekend to allow you to define and plug-in custom serializers.  I'll have to continue to default to hessian for backwards compatibility, but that should provide the hook users will need to change to anything they want.

**Comment by bitsofinfo** [comment]
Sounds good, thanks! I figured back compat would be a concern so you will definately want to make it configurable. Post and update on #81 when you have something to test

**Comment by carterpage** [comment]
Will do.

**Pull request closed without merging**
