### PR TITLE
Add support for SQS subscriptions to SNS topics.

### PR DESCRIPTION
**Pull request by ChrisEineke**
Enable SQS queue subscribers to SNS topics.

### CODE REVIEW

**Comment by carterpage** [comment]
Thanks for submitting a pull request.  Can you please include a unit test with it so we can regress this functionality as part of our future builds?

**Comment by ChrisEineke** [comment]
Yes, I will provide a unit test for it soon.

**Comment by carterpage** [comment]
Thanks!

**Comment by carterpage** [comment]
I'm looking at this some more, and I have to admit I don't know what you are doing.  We have the ability to subscribe to SNS topics in Nevado.  Are you trying to connect to non-Nevado topics?  If so, that isn't currently supported because of the metadata that is required for a JMS implementation.  Since I get this confusion often, I will add it to a FAQ.  If there is actually a bug in the system, please clarify so we can get it fixed.  If I don't hear back, I'll close this out in a couple of weeks.

**Comment by carterpage** [comment]
Please submit again with a unit test that demonstrates what this is fixing.  I need that for regression in case someone else wants to modify the functionality in the future.  Thanks.

**Pull request closed without merging**
